version: '3.9'

services:

  ecommerce_project:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce_app:latest
    command:
      - sleep
      - Infinity
    env_file:
      - ".env"
    volumes:
      - .:/ecommerce
    ports:
      - 8000:8000
    networks:
      - ecommerce-network
    container_name: ecommerce

networks:
  ecommerce-network:
    driver: bridge
