version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    container_name: postgres-db

  app:
    build: 
      - context: .
      - dockerfile: Dockerfile
    command: 'python manage.py runserver 8000'
    ports:
      - '8000:8000'
    depends_on:
      - db
    container_name: ecommerce

volumes:
  postgresql-data:
    driver: local
