version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "0.0.0.0:5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: ecommerce
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    container_name: postgres-db

volumes:
  postgresql-data:
    name: postgres-db
    external: false

networks:
  default:
    