# Generated by Django 4.0.3 on 2022-04-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
