# Generated by Django 4.0.3 on 2022-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=0),
        ),
    ]
