# Generated by Django 4.0.3 on 2022-04-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_address_order_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrdered', models.DateTimeField(auto_now_add=True)),
                ('transactionId', models.CharField(max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('customer_mobile', models.IntegerField(default=0)),
                ('customer_email', models.CharField(max_length=50, null=True)),
                ('customer_address', models.TextField(default=0)),
                ('ordered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.product')),
            ],
        ),
    ]
