# Generated by Django 4.0.3 on 2022-04-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_customer_auth_token_customer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
