# Generated by Django 4.0.3 on 2022-04-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('order_item', models.CharField(default='a', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('dateOrdered', models.DateTimeField(auto_now_add=True)),
                ('transactionId', models.CharField(max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('customer_mobile', models.IntegerField(default=0)),
                ('customer_email', models.CharField(max_length=50, null=True)),
                ('customer_address', models.TextField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('cart_order', 'cart_order'), ('product_order', 'product_order')], default='cart_order', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.product'),
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
