# Generated by Django 4.0.3 on 2022-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_order_cancelled_remove_order_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('cart_order', 'cart_order'), ('product_order', 'product_order')], default='cart_order', max_length=200),
        ),
    ]
