# Generated by Django 4.0.3 on 2022-04-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
