# Generated by Django 4.0.3 on 2022-04-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=0),
        ),
    ]
