# Generated by Django 4.0.3 on 2022-04-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_product_quantity_productorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
